#!/bin/bash

## Description: Init Open Social repository
## Usage: init
## Example: "ddev init"

# Remove any old stuff.
rm -R -f ./vendor
rm -R -f ./docroot
rm -f ./composer.lock

# Install dependencies.
ddev init-site

# Install the profile
if [ "$1" == "demo" ]; then
  echo "Installing Open Social with demo content"
  ddev install demo
else
  echo "Installing Open Social"
  ddev install
fi
