#!/bin/bash

## Description: Install Open Social dependencies
## Usage: init-site
## Example: "ddev init-site"

# Install composer dependencies
composer install

# Create private files directory.
rm -rf /var/www/html/files_private/*
mkdir /var/www/html/files_private

# Create a custom module folder.
mkdir /var/www/html/docroot/modules/custom

# Copy default.settings.php and default.settings.local.php
cp /var/www/html/.ddev/files/default.settings.php /var/www/html/docroot/sites/default/settings.php
cp /var/www/html/.ddev/files/default.settings.local.php /var/www/html/docroot/sites/default/settings.local.php
cp /var/www/html/.ddev/files/settings.ddev.php /var/www/html/docroot/sites/default/settings.ddev.php

# Copy services.yml
cp /var/www/html/.ddev/files/default.services.yml /var/www/html/docroot/sites/default/development.services.yml

# Set up phpunit.
cp /var/www/html/.ddev/files/phpunit.xml.dist /var/www/html/docroot/core/phpunit.xml
