#!/bin/bash

## Description: Run phpstan.
## Usage: phpstan path_to_file
## Example: "ddev phpstan", "ddev phpstan path_to_file_or_folder"

if [ $# -eq 0 ] ; then
  cd docroot && ../vendor/bin/phpstan analyze -c ./profiles/contrib/social/phpstan.neon ./profiles/contrib/social
  exit
else
  path=$@
  prefix1='./'
  prefix2='docroot/'
  relative=${path//$prefix1/}
  relative=${path//$prefix2/}

  cd docroot && ../vendor/bin/phpstan analyze -c ./profiles/contrib/social/phpstan.neon ./${relative}
fi
