#!/bin/bash

## Description: Run phpunit.
## Usage: phpunit path_to_file
## Example: "ddev phpunit", "ddev phpunit path_to_file_or_folder"

if [ $# -eq 0 ] ; then
  cd docroot && ../vendor/bin/phpunit -c core profiles/contrib/social
  exit
else
  path=$@
  prefix1='./'
  prefix2='docroot/'
  relative=${path//$prefix1/}
  relative=${path//$prefix2/}

  cd docroot && ../vendor/bin/phpunit -c core ${relative}
fi
